### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by matheushw** [eduardoadoglio/multiplayer-quiz#2] opened 2021-10-22 00:21 UTC
## Problem
I was expecting to have fun tonight while playing a high-quality game, but the only thing that I found was a huge placeholder text on my screen.

## Solution
I suggest writing some code.

## Inspiration
If you want to check out how to implement a professional game you should check this [repo](https://github.com/matheushw/Jogo_FSI)

## Image
<img width="1440" alt="Screen Shot 2021-10-21 at 21 11 48" src="https://user-images.githubusercontent.com/26571713/138373790-3e19d5c2-1645-4ecf-84de-1ca4d694a6e1.png">

**Comment by eduardoadoglio** [comment] 2021-10-27 23:04
Duplicate of [#5](https://github.com/eduardoadoglio/tic-tac-toe-minimax/issues/5)

**Closed as completed by eduardoadoglio** 2021-10-27 23:04 UTC
Labels: wontfix
